### ISSUE TITLE
Question: can it be altered to output a small sub-set of emoji?

### ISSUE THREAD

**Issue by bigandy** [notwaldorf/emoji-rain#9]
Case : I want to output a small subset of emoji e.g. flags, or weather symbols. Is this possible?

**Comment by notwaldorf** [comment]
Yeah, I think you basically want to override the (`_emoji`)[https://github.com/notwaldorf/emoji-rain/blob/master/emoji-rain.html#L99] array. You can either just extend this element and change it there, or some time after attaching the element to the DOM (so that `connectedCallback` runs), you can do something like `myEmojiRainElement._emoji = [...]`
